InputsS = /eos/cms/store/group/phys_heavyions/wangj/Forest2024PbPb/Dzero_260311-ydiffmva_HiForest_260218_prompt_GNucleusToD0-PhotonBeamA_Bin-Pthat0_Kpi_t2_Dpt-2_Dsize.root
InputsB = /eos/cms/store/group/phys_heavyions/wangj/Forest2025PbPb/Dzero_260311-ydiffmva_PbPbUPC_HIForward0_Dpt-2_ZDCgap-3_Dsize.root, \
          /eos/cms/store/group/phys_heavyions/wangj/Forest2025PbPb/Dzero_260311-ydiffmva_PbPbUPC_HIForward2_Dpt-2_ZDCgap-3_Dsize.root, \
          /eos/cms/store/group/phys_heavyions/wangj/Forest2025PbPb/Dzero_260311-ydiffmva_PbPbUPC_HIForward4_Dpt-2_ZDCgap-3_Dsize.root
InputsMass = /eos/cms/store/group/phys_heavyions/wangj/Forest2025PbPb/Dzero_260426-yrefmva_PbPbUPC_HIForward_Dpt-2_Dsize_12ePD.root
             
Cut = DpassCut23PAS && (Dtrk1PixelHit+Dtrk1StripHit)>=11 && (Dtrk2PixelHit+Dtrk2StripHit)>=11
Label = Cut23PAS